const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, ROOT=__dirname;
const DB=path.join(ROOT,'data.json'), SETTINGS=path.join(ROOT,'settings.json');
const DEFAULT={users:[],rooms:{},history:[],presence:{}};
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(DEFAULT,null,2));
if(!fs.existsSync(SETTINGS))fs.writeFileSync(SETTINGS,JSON.stringify({nextDice:[0,0,0,0]},null,2));
function read(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return {...DEFAULT}}}
function write(x){fs.writeFileSync(DB,JSON.stringify(x,null,2))}
function send(res,code,type,data){res.writeHead(code,{'Content-Type':type,'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'});res.end(data)}
function body(req,cb){let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{cb(JSON.parse(b||'{}'))}catch(e){send(req.res,400,'application/json',JSON.stringify({ok:false,error:'Invalid JSON'}))}})}
function hash(p,s){return crypto.pbkdf2Sync(String(p),s,120000,32,'sha256').toString('hex')}
function token(){return crypto.randomBytes(24).toString('hex')}
function code(){return crypto.randomBytes(3).toString('hex').toUpperCase()}
function user(req){const t=(req.headers.authorization||'').replace('Bearer ','');let d=read();return d.users.find(u=>u.token===t)}
function gameDefault(P=2){return {P,names:['Player 1','Player 2','Player 3','Player 4'],state:Array.from({length:P},()=>[-1,-1,-1,-1]),turn:0,dice:0,lastDice:[0,0,0,0],mustMove:false,over:false,moving:false}}
function resetRoom(r){r.game=gameDefault(r.P);r.adminDice=[0,0,0,0];r.status=r.players.length>=r.P?'playing':'waiting';r.paused=false;r.lastActive=new Date().toISOString();}
function getRoom(d,c){return d.rooms[c]}
const server=http.createServer((req,res)=>{
 if(req.method==='OPTIONS')return send(res,204,'text/plain','');
 const url=new URL(req.url,'http://localhost'), p=url.pathname;
 if(p==='/api/auth/register'&&req.method==='POST')return body(req,x=>{let d=read(),name=String(x.username||'').trim().slice(0,24),pass=String(x.password||'');if(name.length<3||pass.length<4)return send(res,400,'application/json',JSON.stringify({ok:false,error:'Username 3+ and password 4+'}));if(d.users.some(u=>u.username.toLowerCase()===name.toLowerCase()))return send(res,409,'application/json',JSON.stringify({ok:false,error:'Username already exists'}));let salt=crypto.randomBytes(16).toString('hex'),u={id:crypto.randomUUID(),username:name,salt,hash:hash(pass,salt),token:token(),createdAt:new Date().toISOString(),lastActive:new Date().toISOString(),games:0,wins:0,blocked:false};d.users.push(u);write(d);send(res,200,'application/json',JSON.stringify({ok:true,token:u.token,user:{id:u.id,username:u.username}}))});
 if(p==='/api/auth/guest'&&req.method==='POST')return body(req,x=>{let d=read(),u={id:'guest_'+crypto.randomUUID(),username:'Guest '+code(),salt:'',hash:'',token:token(),createdAt:new Date().toISOString(),lastActive:new Date().toISOString(),games:0,wins:0,blocked:false,guest:true};d.users.push(u);write(d);send(res,200,'application/json',JSON.stringify({ok:true,token:u.token,user:{id:u.id,username:u.username,guest:true}}))});
 if(p==='/api/auth/login'&&req.method==='POST')return body(req,x=>{let d=read(),u=d.users.find(u=>u.username.toLowerCase()===String(x.username||'').toLowerCase());if(!u||u.blocked||hash(String(x.password||''),u.salt)!==u.hash)return send(res,401,'application/json',JSON.stringify({ok:false,error:'Invalid login'}));u.token=token();u.lastActive=new Date().toISOString();write(d);send(res,200,'application/json',JSON.stringify({ok:true,token:u.token,user:{id:u.id,username:u.username}}))});
 if(p==='/api/me'&&req.method==='GET'){let u=user(req);return send(res,u?200:401,'application/json',JSON.stringify(u?{ok:true,user:{id:u.id,username:u.username}}:{ok:false}))}
 if(p==='/api/rooms'&&req.method==='POST')return body(req,x=>{let u=user(req);if(!u)return send(res,401,'application/json','{"ok":false,"error":"Login required"}');let d=read(),c=code();while(d.rooms[c])c=code();let P=x.P===4?4:2;d.rooms[c]={code:c,host:u.id,P,players:[{userId:u.id,username:u.username,index:0,joinedAt:new Date().toISOString()}],game:gameDefault(P),createdAt:new Date().toISOString(),lastActive:new Date().toISOString(),status:'waiting',adminDice:[0,0,0,0]};write(d);send(res,200,'application/json',JSON.stringify({ok:true,room:c,index:0,P}))});
 if(p==='/api/rooms/join'&&req.method==='POST')return body(req,x=>{let u=user(req),c=String(x.room||'').toUpperCase();if(!u)return send(res,401,'application/json','{"ok":false,"error":"Login required"}');let d=read(),r=d.rooms[c];if(!r)return send(res,404,'application/json','{"ok":false,"error":"Room not found"}');let ex=r.players.find(q=>q.userId===u.id);if(ex)return send(res,200,'application/json',JSON.stringify({ok:true,room:c,index:ex.index,P:r.P}));if(r.players.length>=r.P)return send(res,409,'application/json','{"ok":false,"error":"Room full"}');let idx=r.players.length;r.players.push({userId:u.id,username:u.username,index:idx,joinedAt:new Date().toISOString()});if(!r.game||!Array.isArray(r.game.state)||r.game.state.length!==r.P)r.game=gameDefault(r.P);r.status=r.players.length>=r.P?'playing':'waiting';r.lastActive=new Date().toISOString();write(d);send(res,200,'application/json',JSON.stringify({ok:true,room:c,index:idx,P:r.P,status:r.status}))});
 if(p==='/api/rooms/leave'&&req.method==='POST')return body(req,x=>{let u=user(req),c=String(x.room||'').toUpperCase();if(!u)return send(res,401,'application/json','{"ok":false,"error":"Login required"}');let d=read(),r=d.rooms[c];if(!r)return send(res,404,'application/json','{"ok":false,"error":"Room not found"}');let idx=r.players.findIndex(q=>q.userId===u.id);if(idx<0)return send(res,200,'application/json','{"ok":true}');r.players.splice(idx,1);r.players.forEach((q,i)=>q.index=i);if(r.host===u.id){r.host=r.players[0]?.userId||'';}if(r.players.length===0){delete d.rooms[c];delete d.presence[u.id];write(d);return send(res,200,'application/json','{"ok":true,"deleted":true}')}r.status=r.game?.over?'finished':(r.players.length>=r.P?'playing':'waiting');r.lastActive=new Date().toISOString();if(r.game){r.game.status=r.status;if(r.players.length<r.P){r.game=gameDefault(r.P)}}delete d.presence[u.id];write(d);send(res,200,'application/json',JSON.stringify({ok:true,room:c,status:r.status}));});
 if(p==='/api/rooms'&&req.method==='GET'){let u=user(req),d=read(),c=String(url.searchParams.get('room')||'').toUpperCase(),r=d.rooms[c];if(!r)return send(res,404,'application/json','{"ok":false}');send(res,200,'application/json',JSON.stringify({ok:true,room:{code:c,P:r.P,host:r.host,players:r.players,status:r.status,createdAt:r.createdAt,lastActive:r.lastActive}}));return}
 if(p==='/api/game'&&req.method==='GET'){let c=String(url.searchParams.get('room')||'').toUpperCase(),d=read(),r=d.rooms[c];if(!r)return send(res,404,'application/json','{"ok":false}');r.lastActive=new Date().toISOString();write(d);return send(res,200,'application/json',JSON.stringify({...r.game,paused:!!r.paused}))}
 if(p==='/api/game'&&req.method==='POST')return body(req,x=>{let u=user(req),c=String(url.searchParams.get('room')||'').toUpperCase(),d=read(),r=d.rooms[c];if(!u||!r)return send(res,401,'application/json','{"ok":false,"error":"Login/room required"}');let pl=r.players.find(q=>q.userId===u.id);if(!pl)return send(res,403,'application/json','{"ok":false,"error":"Not in room"}');if(!Array.isArray(x.state))return send(res,400,'application/json','{"ok":false,"error":"Invalid game"}');let old=r.game||gameDefault(r.P);if(r.status==='playing' && Array.isArray(old.state) && old.state.length && pl.index!==Number(old.turn))return send(res,409,'application/json','{"ok":false,"error":"Not your turn"}');let state=Array.from({length:r.P},(_,i)=>Array.from({length:4},(_,t)=>{let n=Number(Array.isArray(x.state[i])?x.state[i][t]:-1);return Number.isFinite(n)?Math.max(-1,Math.min(57,n)):-1;}));let newTurn=Math.max(0,Math.min(r.P-1,Number.isFinite(Number(x.turn))?Number(x.turn):old.turn));r.game={P:r.P,names:Array.isArray(x.names)?x.names.slice(0,4):old.names,state,turn:newTurn,dice:Math.max(0,Math.min(6,Number(x.dice)||0)),lastDice:Array.isArray(x.lastDice)?x.lastDice.slice(0,4):old.lastDice,mustMove:!!x.mustMove,over:!!x.over,moving:!!x.moving};r.status=r.paused?'paused':(r.game.over?'finished':(r.players.length>=r.P?'playing':'waiting'));r.lastActive=new Date().toISOString();u.lastActive=r.lastActive; if(r.game.over&&!old.over){let winner=r.game.turn; if(Array.isArray(r.game.state)) winner=r.game.state.findIndex(a=>Array.isArray(a)&&a.every(v=>v>=57)); let rec={id:crypto.randomUUID(),room:c,winner:Math.max(0,winner),names:r.game.names,players:r.players.map(q=>q.username),endedAt:r.lastActive};d.history.unshift(rec);d.history=d.history.slice(0,500);r.players.forEach(q=>{let uu=d.users.find(z=>z.id===q.userId);if(uu){uu.games++;if(q.index===winner)uu.wins++}})}write(d);send(res,200,'application/json','{"ok":true}')});
 if(p==='/api/presence'&&req.method==='POST')return body(req,x=>{let u=user(req);if(!u)return send(res,401,'application/json','{"ok":false}');let d=read();d.presence[u.id]={username:u.username,room:String(x.room||''),player:Number(x.player)||0,lastSeen:new Date().toISOString(),ip:req.socket.remoteAddress};u.lastActive=d.presence[u.id].lastSeen;write(d);send(res,200,'application/json','{"ok":true}')});
 if(p==='/api/settings'&&req.method==='GET')return send(res,200,'application/json',fs.readFileSync(SETTINGS,'utf8'));
 if(p==='/api/settings'&&req.method==='POST')return body(req,x=>{if(!adminOK())return send(res,401,'application/json','{"ok":false,"error":"Admin required"}');let nextDice=Array.isArray(x.nextDice)?x.nextDice.slice(0,4).map(n=>Math.max(0,Math.min(6,parseInt(n)||0))):[0,0,0,0];fs.writeFileSync(SETTINGS,JSON.stringify({nextDice},null,2));send(res,200,'application/json',JSON.stringify({ok:true,nextDice}))});
 if(p==='/api/dice/consume'&&req.method==='POST')return body(req,x=>{let u=user(req),c=String(x.room||'').toUpperCase(),d=read(),r=d.rooms[c],i=Math.max(0,Math.min(3,parseInt(x.player)||0));if(!u||!r)return send(res,401,'application/json','{"ok":false}');if(!r.players.some(q=>q.userId===u.id))return send(res,403,'application/json','{"ok":false}');let arr=Array.isArray(r.adminDice)?r.adminDice:[0,0,0,0],value=arr[i]||0;arr[i]=0;r.adminDice=arr;r.lastActive=new Date().toISOString();write(d);send(res,200,'application/json',JSON.stringify({ok:true,value}))});
 if(p==='/api/admin/room-dice'&&req.method==='POST')return body(req,x=>{if(!adminOK())return send(res,401,'application/json','{"ok":false}');let d=read(),c=String(x.room||'').toUpperCase(),r=d.rooms[c],i=Math.max(0,Math.min(3,parseInt(x.player)||0)),v=Math.max(0,Math.min(6,parseInt(x.value)||0));if(!r)return send(res,404,'application/json','{"ok":false,"error":"Room not found"}');if(!Array.isArray(r.adminDice))r.adminDice=[0,0,0,0];r.adminDice[i]=v;r.lastActive=new Date().toISOString();r.adminControl={action:'set-dice',player:i,value:v,at:r.lastActive};write(d);send(res,200,'application/json',JSON.stringify({ok:true,room:c,player:i,value:v,adminDice:r.adminDice}))});
 if(p==='/api/admin/login'&&req.method==='POST')return body(req,x=>{let pw=process.env.ADMIN_PASSWORD||'change-me-123';if(String(x.password||'')!==pw)return send(res,401,'application/json','{"ok":false,"error":"Wrong admin password"}');let t=token();let d=read();d.adminToken=t;write(d);send(res,200,'application/json',JSON.stringify({ok:true,token:t}))});
 function adminOK(){let d=read();return (req.headers.authorization||'').replace('Bearer ','')===d.adminToken}
 if(p==='/api/admin/data'&&req.method==='GET'){if(!adminOK())return send(res,401,'application/json','{"ok":false}');let d=read(),now=Date.now(),online=Object.values(d.presence).filter(x=>now-Date.parse(x.lastSeen)<30000);let users=d.users.map(u=>({id:u.id,username:u.username,createdAt:u.createdAt,lastActive:u.lastActive,games:u.games,wins:u.wins,blocked:u.blocked,guest:!!u.guest}));let rooms=Object.values(d.rooms).map(r=>({code:r.code,P:r.P,status:r.status,host:r.host,players:r.players,lastActive:r.lastActive,game:r.game,adminDice:Array.isArray(r.adminDice)?r.adminDice:[0,0,0,0]}));return send(res,200,'application/json',JSON.stringify({ok:true,stats:{users:users.length,online:online.length,rooms:rooms.length,running:rooms.filter(r=>r.status==='playing').length,games:d.history.length},users,online,rooms,history:d.history,settings:JSON.parse(fs.readFileSync(SETTINGS,'utf8'))}))}
 if(p==='/api/admin/user'&&req.method==='POST')return body(req,x=>{if(!adminOK())return send(res,401,'application/json','{"ok":false}');let d=read(),u=d.users.find(z=>z.id===x.id);if(!u)return send(res,404,'application/json','{"ok":false}');u.blocked=!!x.blocked;write(d);send(res,200,'application/json','{"ok":true}')});
 if(p==='/api/admin/room'&&req.method==='POST')return body(req,x=>{if(!adminOK())return send(res,401,'application/json','{"ok":false}');let d=read(),r=d.rooms[String(x.room||'').toUpperCase()];if(!r)return send(res,404,'application/json','{"ok":false,"error":"Room not found"}');let action=String(x.action||'');if(action==='reset'){resetRoom(r)}else if(action==='pause'){r.paused=true;r.status='paused';r.lastActive=new Date().toISOString()}else if(action==='resume'){r.paused=false;r.status=r.game.over?'finished':(r.players.length>=r.P?'playing':'waiting');r.lastActive=new Date().toISOString()}else if(action==='clear-dice'){r.adminDice=[0,0,0,0];r.adminControl={action:'clear-dice',at:new Date().toISOString()};r.lastActive=r.adminControl.at}else if(action==='force-turn'){let i=Math.max(0,Math.min(r.P-1,parseInt(x.player)||0));r.game.turn=i;r.game.dice=0;r.game.mustMove=false;r.game.moving=false;r.game.lastDice=Array.isArray(r.game.lastDice)?r.game.lastDice:[0,0,0,0];r.lastActive=new Date().toISOString()}
else if(action==='kick'){let id=String(x.userId||'');r.players=r.players.filter(q=>q.userId!==id);if(!r.players.length){delete d.rooms[r.code]}else{r.players.forEach((q,i)=>q.index=i);r.status=r.paused?'paused':(r.game.over?'finished':(r.players.length>=r.P?'playing':'waiting'));r.lastActive=new Date().toISOString()}}else if(action==='close'){delete d.rooms[r.code]}else return send(res,400,'application/json','{"ok":false,"error":"Unknown action"}');write(d);send(res,200,'application/json','{"ok":true}')});
 if(p==='/api/admin/user-delete'&&req.method==='POST')return body(req,x=>{if(!adminOK())return send(res,401,'application/json','{"ok":false}');let d=read(),id=String(x.id||'');if(Object.values(d.rooms).some(r=>r.players.some(q=>q.userId===id)))return send(res,409,'application/json','{"ok":false,"error":"User is in a live room"}');d.users=d.users.filter(u=>u.id!==id);delete d.presence[id];write(d);send(res,200,'application/json','{"ok":true}')});
 if(p==='/api/admin/announcement'&&req.method==='POST')return body(req,x=>{if(!adminOK())return send(res,401,'application/json','{"ok":false}');let d=read();d.announcement={text:String(x.text||'').slice(0,500),at:new Date().toISOString()};write(d);send(res,200,'application/json',JSON.stringify({ok:true,announcement:d.announcement}))});
 if(p==='/api/announcement'&&req.method==='GET'){let d=read();return send(res,200,'application/json',JSON.stringify({ok:true,announcement:d.announcement||null}))}
 let u=url.pathname.split('?')[0];if(u==='/')u='/index.html';const file=path.join(ROOT,u);if(!file.startsWith(ROOT)||!fs.existsSync(file))return send(res,404,'text/plain','Not found');const ext=path.extname(file),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.txt':'text/plain'};send(res,200,types[ext]||'application/octet-stream',fs.readFileSync(file));
});server.listen(PORT,()=>console.log(`Royal Ludo server running on http://0.0.0.0:${PORT}`));
